### PR TITLE
see how this goes

### PR DESCRIPTION
**Pull request by LewisTehMinerz**
this should fix it. if it's null, it will replace the avy with an unknown user avy.
@Fires1

### CODE REVIEW

**Comment by LewisTehMinerz** [comment]
ignore circleci, it's garbage.

**Comment by Fires1** [comment]
why not just a null check?

**Comment by LewisTehMinerz** [comment]
trying to at least have a placeholder.

also it's just kind of better practice to use an if statement on something you know will be null.

**Comment by Fires1** [comment]
What?

It says in the D.net docs that if the user has the default discord profile picture, it WILL be null. There is literally NO FUCKING REASON to use try catch.

Its even better **since thats the wrong error**. Its a *null reference* not an argument null bullshit.

It would have been easier just to make a quick null check with an if statement then write some try catch bullshit.

Do you not know anything about C#??????

**Comment by LewisTehMinerz** [comment]
so wait, what are you moaning at me for. not using an if statement or using a try/catch

**Comment by Fires1** [comment]
both, because both are idiotic

**Comment by LewisTehMinerz** [comment]
then how the fuck am i supposed to do it?

tell me how you would do it.

**Comment by Fires1** [comment]
if  (Context.User.GetAvatarUrl()==null)
//do nothing
else
 builder.ThumbnailUrl = new Uri(Context.User.GetAvatarUrl());

**Comment by LewisTehMinerz** [comment]
1. you just used an if statement, which you just said was garbage
2. read the title of #26.
"System.ArgumentNullException"

also are you mad at something?

**Comment by Fires1** [comment]
"so wait, what are you moaning at me for. **not using an if statement** or using a try/catch"

Exceptions are expensive and a heavy hit on performance. You would never use them in decision making code. Thats awful

**Comment by LewisTehMinerz** [comment]
oh i'm sorry, i misread it.

i thought that it was the Uri throwing the exception, not that the actual argument was null.
that is why i put the original try/catch
but ok
commit is fixed
you can merge it

**Comment by Fires1** [comment]
**It says in the D.net docs that if the user has the default discord profile picture, it WILL be null. There is literally NO FUCKING REASON to use try catch.**

do you even fucking read

**Comment by LewisTehMinerz** [comment]
this is valid

**Comment by Fires1** [comment]
stop.

**Comment by LewisTehMinerz** [comment]
it feels like you don't want me around anymore.
like seriously, since you banned me then unbanned me you've never really been supporting me.
it really makes me feel like you want me to leave.
if that is what you want, it's fine.

**Pull request closed without merging**
